server:
  port: 8080

rest.client:
  cards.url: http://localhost:8081
  
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 20000
hystrix.command.default.execution.timeout.enabled: false

logging:
  level:
    org:
      springframework:
        web: DEBUG